### ISSUE TITLE
(libuv) Failed to create kqueue (24)

### ISSUE THREAD

**Issue by turingou** [eviltik/evilscan#30]
have you guys ever meet this error when running CLI ?

````
$ evilscan 192.168.1.0/24 --port=8080
````

then error happend:

````
(libuv) Failed to create kqueue (24)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EBADF
    at errnoException (net.js:901:11)
    at WriteStream.Socket._write (net.js:643:26)
    at doWrite (_stream_writable.js:219:10)
    at writeOrBuffer (_stream_writable.js:209:5)
    at WriteStream.Writable.write (_stream_writable.js:180:11)
    at WriteStream.Socket.write (net.js:613:40)
    at null.<anonymous> (/usr/local/lib/node_modules/evilscan/bin/evilscan.js:19:28)
    at EventEmitter.emit (events.js:95:17)
    at /usr/local/lib/node_modules/evilscan/main.js:377:18
    at /usr/local/lib/node_modules/evilscan/node_modules/async/lib/async.js:229:13
````

node version: v0.10.12
npm version: 1.2.32
evilscan version: lastest (0.0.9)

**Comment by eviltik** [comment]
closing ticket because no response
